// eslint.config.mjs
import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  // Ignore generated / build / static assets
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'dist/**',
      'out/**',
      'coverage/**',
      'drizzle/**',
      'public/**',
      'next-env.d.ts', // generated by Next (contains triple-slash refs)
    ],
  },

  // Next.js + TS recommended
  ...compat.extends('next/core-web-vitals', 'next/typescript'),

  // (Optional) turn off triple-slash check in any *.d.ts you own
  { files: ['**/*.d.ts'], rules: { '@typescript-eslint/triple-slash-reference': 'off' } },

  // Path alias resolution for import linting
  {
    settings: {
      'import/resolver': {
        typescript: { project: './tsconfig.json' },
      },
    },
  },
];

export default eslintConfig;
